accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('pages.urls', namespace='pages')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('schools/', include('schools.urls', namespace='schools')),
    path('tutors/', include('tutors.urls', namespace='tutors')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('<int:course_id>/', views.course, name='course'),
    path('search/', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('copyright/', views.copyright, name='copyright'),
    path('terms_of_use/', views.terms_of_use, name='terms_of_use'),
    path('privacy/', views.privacy, name='privacy'),
]

schools/urls.py
from django.urls import path
from . import views

app_name = 'schools'

urlpatterns = [
    path('', views.schools, name='schools'),
    path('<int:school_id>/', views.school, name='school'),
]

tutors/urls.py
from django.urls import path
from . import views

app_name = 'tutors'

urlpatterns = [
    path('', views.tutors, name='tutors'),
    path('<int:tutor_id>/', views.tutor, name='tutor'),
]

templates/partials/_footer.html
{% load static %}
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}"
      rel="stylesheet"
      type="text/css">
<!--Footer-->
<footer class="footer">
    <div class="footer_background"
         style="background-image:url('{% static 'images/footer_background.png' %}')"></div>
    <div class="container">
        <div class="row footer_row">
            <div class="col">
                <div class="footer_content">
                    <div class="row">
                        <div class="col-lg-3 footer_col">
                            <!-- Footer About -->
                            <div class="footer_section footer_about">
                                <div class="footer_logo_container">
                                    <a href="#">
                                        <div class="footer_logo_text">
                                            Tutor<span>5**</span>
                                        </div>
                                    </a>
                                </div>
                                <div class="footer_about_text">
                                    <p>Join us. Let's march to the road of 5** together.</p>
                                </div>
                                <div class="footer_social">
                                    <ul>
                                        <li>
                                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                        </li>
                                        <li>
                                            <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                                        </li>
                                        <li>
                                            <a href="https://www.instagram.com/tutorstar2025/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                                        </li>
                                        <li>
                                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 footer_col">
                            <!-- Footer Contact -->
                            <div class="footer_section footer_contact">
                                <div class="footer_title">Contact Info</div>
                                <div class="footer_contact_info">
                                    <ul>
                                        <li>Email: tutorstar2025@gmail.com</li>
                                        <li>Phone:  +(852) 88888888</li>
                                        <li>Kwan Chung Tung, Hong Kong</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 footer_col">
                            <!-- Footer links -->
                            <div class="footer_section footer_links">
                                <div class="footer_title">Quick Links</div>
                                <div class="footer_links_container">
                                    <ul>
                                        <li>
                                            <a href="{% url 'pages:index' %}">Home</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'pages:about' %}">About</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'tutors:tutors' %}">Tutors</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'pages:contact' %}">Contact Us</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'courses:courses' %}">Courses</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'schools:schools' %}">Schools</a>
                                        </li>
                                        <li>
                                            <a href="#">TBA</a>
                                        </li>
                                        <li>
                                            <a href="#">TBA</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 footer_col clearfix">
                            <!-- Footer links -->
                            <div class="footer_section footer_mobile">
                                <div class="footer_title">Download App</div>
                                <div class="footer_mobile_content">
                                    <div class="footer_image">
                                        <a href="#">
                                            <img src="{% static 'images/mobile_1.png' %}" alt="">
                                        </a>
                                    </div>
                                    <div class="footer_image">
                                        <a href="#">
                                            <img src="{% static 'images/mobile_2.png' %}" alt="">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row copyright_row">
            <div class="col">
                <div class="copyright d-flex flex-lg-row flex-column align-items-center justify-content-start">
                    <div class="cr_text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                    <div class="ml-lg-auto cr_links">
                        <ul class="cr_list">
                            <li>
                                <a href="{% url 'pages:copyright' %}">Copyright notification</a>
                            </li>
                            <li>
                                <a href="{% url 'pages:terms_of_use' %}">Terms of Use</a>
                            </li>
                            <li>
                                <a href="{% url 'pages:privacy' %}">Privacy Policy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
</div>

templates/partials/_menubar.html
<!-- Menu -->
<div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
    <div class="menu_close_container">
        <div class="menu_close">
            <div></div>
            <div></div>
        </div>
    </div>
    <div class="search">
        <form action="#" class="header_search_form menu_mm">
            <input type="search"
                   class="search_input menu_mm"
                   placeholder="Search"
                   required="required">
            <button class="header_search_button d-flex flex-column align-items-center justify-content-center menu_mm">
                <i class="fa fa-search menu_mm" aria-hidden="true"></i>
            </button>
        </form>
    </div>
    <nav class="menu_nav">
        <ul class="menu_mm">
            <li class="menu_mm">
                <a href="{% url 'pages:index' %}">Home</a>
            </li>
            <li class="menu_mm">
                <a href="{% url 'pages:about' %}">About</a>
            </li>
            <li class="menu_mm">
                <a href="{% url 'courses:courses' %}">Courses</a>
            </li>
            <li class="menu_mm">
                <a href="{% url 'tutors:tutors' %}">Tutors</a>
            </li>
            <li class="menu_mm">
                <a href="{% url 'schools:schools' %}">Schools</a>
            </li>
            <li class="menu_mm">
                <a href="{% url 'pages:contact' %}">Contact Us</a>
            </li>
        </ul>
    </nav>
</div>

templates/partials/_subcribebar.html
{% load static %}
<!-- Newsletter -->

	<div class="newsletter">
		<div class="newsletter_background parallax-window" data-parallax="scroll" data-image-src={% static "images/newsletter.jpg"%}  data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="newsletter_container d-flex flex-lg-row flex-column align-items-center justify-content-start">

						<!-- Newsletter Content -->
						<div class="newsletter_content text-lg-left text-center">
							<div class="newsletter_title">sign up for news and offers</div>
							<div class="newsletter_subtitle">Subcribe to lastest smartphones news & great deals we offer</div>
						</div>

						<!-- Newsletter Form -->
						<div class="newsletter_form_container ml-lg-auto">
							<form action="#" id="newsletter_form" class="newsletter_form d-flex flex-row align-items-center justify-content-center">
								<input type="email" class="newsletter_input" placeholder="Your Email" required="required">
								<button type="submit" class="newsletter_button">subscribe</button>
							</form>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

templates/partials/_topbar.html
<div class="super_container">
    <!-- Header -->
    <header class="header">
        <!-- Top Bar -->
        <div class="top_bar">
            <div class="top_bar_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="top_bar_content d-flex flex-row align-items-center justify-content-start">
                                <ul class="top_bar_contact_list">
                                    <li>
                                        <div class="question">Have any questions?</div>
                                    </li>
                                    <li>
                                        <i class="fa fa-phone" aria-hidden="true"></i>
                                        <div>+(852) 88888888</div>
                                    </li>
                                    <li>
                                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                                        <div>tutorstar2025@gmail.com</div>
                                    </li>
                                </ul>
                                <div class="ml-auto">
                                    <div class="d-flex justify-content-between" style="gap: 10px;">
                                        {% if user.is_authenticated %}
                                            <div class="btn-group" role="group" aria-label="Dashboard and Logout">
                                                <a href="{% url 'accounts:dashboard' %}" class="btn btn-primary">
                                                    <i class="fas fa-tachometer-alt"></i> Dashboard
                                                </a>
                                            </div>
                                            <div class="btn-group" role="group" aria-label="Logout">
                                                <form action="{% url 'accounts:logout' %}"
                                                      method="POST"
                                                      style="display:inline">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-danger">
                                                        <i class="fas fa-sign-out-alt"></i> Logout
                                                    </button>
                                                </form>
                                            </div>
                                        {% else %}
                                            <div class="btn-group" role="group" aria-label="Register">
                                                <a href="{% url 'accounts:register' %}" class="btn btn-success">
                                                    <i class="fa fa-user-plus"></i> Register
                                                </a>
                                            </div>
                                            <div class="btn-group" role="group" aria-label="Login">
                                                <a href="{% url 'accounts:login' %}" class="btn btn-primary">
                                                    <i class="fas fa-sign-in-alt"></i> Login
                                                </a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Header Content -->
            <div class="header_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="header_content d-flex flex-row align-items-center justify-content-start">
                                <div class="logo_container">
                                    <a href="#">
                                        <div class="logo_text">
                                            Tutor<span>5**</span>
                                        </div>
                                    </a>
                                </div>
                                <nav class="main_nav_contaner ml-auto">
                                    <ul class="main_nav">
                                        <li {% if request.path == '/' %}class="active"{% endif %}>
                                            <a href="{% url 'pages:index' %}">Home</a>
                                        </li>
                                        <li {% if request.path == '/about/' %}class="active"{% endif %}>
                                            <a href="{% url 'pages:about' %}">About</a>
                                        </li>
                                        <li {% if request.path == '/courses/' %}class="active"{% endif %}>
                                            <a href="{% url 'courses:courses' %}">Courses</a>
                                        </li>
                                        <li {% if request.path == '/tutors/' %}class="active"{% endif %}>
                                            <a href="{% url 'tutors:tutors' %}">Tutors</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'schools:schools' %}">Schools</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'pages:contact' %}">Contact Us</a>
                                        </li>
                                    </ul>
                                    <div class="search_button">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                    </div>
                                    <!-- Hamburger -->
                                    <div class="shopping_cart">
                                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    </div>
                                    <div class="hamburger menu_mm">
                                        <i class="fa fa-bars menu_mm" aria-hidden="true"></i>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Header Search Panel -->
            <div class="header_search_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="header_search_content d-flex flex-row align-items-center justify-content-end">
                                <form action="{% url 'courses:search' %}" class="header_search_form">
                                    <input type="search"
                                           class="search_input"
                                           placeholder="Search"
                                           required="required"
                                           name="keywords">
                                    <button class="header_search_button d-flex flex-column align-items-center justify-content-center">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>