config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('pages.urls', namespace='pages')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('schools/', include('schools.urls', namespace='schools')),
    path('tutors/', include('tutors.urls', namespace='tutors')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('<int:course_id>/', views.course, name='course'),
    path('search/', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('copyright/', views.copyright, name='copyright'),
    path('terms_of_use/', views.terms_of_use, name='terms_of_use'),
    path('privacy/', views.privacy, name='privacy'),
]

tutors/urls.py
from django.urls import path
from . import views

app_name = 'tutors'

urlpatterns = [
    path('', views.tutors, name='tutors'),
    path('<int:tutor_id>/', views.tutor, name='tutor'),
]

tutors/models.py
from django.db import models
from datetime import datetime
from courses.choices import subject_choices
# Create your models here.


class Tutor(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=20, default='00000000')
    email = models.EmailField(max_length=50, unique=False, blank=True)
    is_mvp = models.BooleanField(default=True)
    hire_date = models.DateTimeField(auto_now_add=True)
    course_subject = models.CharField(max_length=50,
                                      choices=subject_choices,
                                      default='Chinese',
                                      help_text='Subject taught by the tutor'
                                      )
    rating = models.DecimalField(
        max_digits=2,
        decimal_places=1,
        default=0.0,
        help_text='Average rating from 0.0 to 5.0'
    )
    experience = models.CharField(
        max_length=20,
        default=1,
        help_text='Years of experience'
    )
    taught_students = models.PositiveIntegerField(
        default=100,
        help_text='Number of students taught'
    )

    def __str__(self):
        return self.name

tutors/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Tutor
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def tutors(request):
    tutors = Tutor.objects.all()
    items_per_page = int(request.GET.get('items_per_page', 4))
    paginator = Paginator(tutors, items_per_page)
    page = request.GET.get('page', 1)
    paged_tutors = paginator.get_page(page)
    context = {
        'tutors': paged_tutors,

    }
    return render(request, 'tutors/tutors.html', context)


def tutor(request, tutor_id):
    tutor = Tutor.objects.get(id=tutor_id)
    return render(request, 'tutors/tutor.html', {'tutor': tutor})

templates/tutors/tutor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  | Tutors - {{ tutor.name }}
{% endblock title %}
{% block link %}
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
  <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}"
        rel="stylesheet"
        type="text/css">
  <link href="{% static 'plugins/colorbox/colorbox.css' %}"
        rel="stylesheet"
        type="text/css">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'styles/course.css' %}">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'styles/course_responsive.css' %}">
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock link %}
{% block content %}
  <!-- Home (breadcrumbs)-->
  <div class="home">
    <div class="breadcrumbs_container">
      <div class="container" style="background-color: transparent;">
        <div class="row">
          <div class="col">
            <div class="breadcrumbs">
              <ul>
                <li>
                  <a href="{% url 'pages:index' %}">Home</a>
                </li>
                <li>
                  <a href="{% url 'courses:courses' %}">Courses</a>
                </li>
                <li>{{ tutor.name }}</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Tutor Profile -->
  <div class="container-fluid tutor-profile-container"
       style="background-image: url('{% static 'images/tutor_bg.png' %}');
              background-size: cover;
              background-position: center;
              background-repeat: no-repeat;
              min-height: 100vh;
              display: flex;
              align-items: center;
              justify-content: center">
    <div class="container tutor-profile-content p-5 rounded"
         style="max-width: 800px">
      <div class="text-center">
        <!-- Main Photo -->
        <img src="{{ tutor.photo.url }}"
             alt="{{ tutor.name }}"
             class="img-fluid rounded-circle mb-4"
             style="width: 200px;
                    height: 200px;
                    object-fit: cover">
        <h1 class="mb-3">{{ tutor.name }}</h1>
        {% if tutor.is_mvp %}<span class="badge bg-warning text-dark mb-3">🌟 MVP Tutor</span>{% endif %}
        <!-- Basic Info -->
        <div class="tutor-details mb-4">
          <p>
            <strong>Subject:</strong> {{ tutor.course_subject }}
          </p>
          <p>
            <strong>Rating:</strong> {{ tutor.rating }}/5.0
          </p>
          <p>
            <strong>Experience:</strong> {{ tutor.experience }} years
          </p>
          <p>
            <strong>Students Taught:</strong> {{ tutor.taught_students }}+
          </p>
          <p>
            <strong>Member Since:</strong> {{ tutor.hire_date|date:"F Y" }}
          </p>
        </div>
        <!-- Contact Info -->
        <div class="contact-info mb-4 p-3 bg-light rounded">
          <h4>Contact</h4>
          <p>
            <i class="fa fa-phone"></i> {{ tutor.phone }}
          </p>
          <p>
            <i class="fa fa-envelope"></i> <a href="mailto:{{ tutor.email }}">{{ tutor.email }}</a>
          </p>
        </div>
        <!-- Additional Photos -->
        {% if tutor.photo_1 or tutor.photo_2 or tutor.photo_3 %}
          <div class="additional-photos mb-4">
            <h4>Gallery</h4>
            <div class="row">
              {% if tutor.photo_1 %}
                <div class="col-md-4 mb-3">
                  <img src="{{ tutor.photo_1.url }}" class="img-thumbnail">
                </div>
              {% endif %}
              {% if tutor.photo_2 %}
                <div class="col-md-4 mb-3">
                  <img src="{{ tutor.photo_2.url }}" class="img-thumbnail">
                </div>
              {% endif %}
              {% if tutor.photo_3 %}
                <div class="col-md-4 mb-3">
                  <img src="{{ tutor.photo_3.url }}" class="img-thumbnail">
                </div>
              {% endif %}
            </div>
          </div>
        {% endif %}
        <!-- Description -->
        <div class="tutor-bio mb-4">
          <h3>About Me</h3>
          <p class="text-muted">{{ tutor.description }}</p>
        </div>
        <a href="{% url 'tutors:tutors' %}" class="btn btn-primary">← Back to All Tutors</a>
      </div>
    </div>
  </div>
{% endblock content %}
{% block script %}
  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
  <script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
  <script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
  <script src="{% static 'plugins/easing/easing.js' %}"></script>
  <script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
  <script src="{% static 'plugins/colorbox/jquery.colorbox-min.js' %}"></script>
  <script src="{% static 'js/course.js' %}"></script>
{% endblock script %}

templates/tutors/tutors.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  | Tutors
{% endblock title %}
{% block link %}
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
  <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}"
        rel="stylesheet"
        type="text/css">
  <link href="{% static 'plugins/colorbox/colorbox.css' %}"
        rel="stylesheet"
        type="text/css">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'styles/courses.css' %}">
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'styles/courses_responsive.css' %}">
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock link %}
{% block content %}
  <!-- Home -->
  <div class="home">
    <div class="breadcrumbs_container">
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="breadcrumbs">
              <ul>
                <li>
                  <a href="{% url 'pages:index' %}">Home</a>
                </li>
                <li>Tutors</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--Tutors-->
  <div class="container"
       style="background-image: url('{% static 'images/video_bg.png' %}');
              background-size: cover;
              background-position: center;
              background-repeat: no-repeat;
              padding: 20px">
    <div class="display-4" style="color: #fff;">Our Tutors</div>
    <div class="row">
      {% for tutor in tutors %}
        <div class="col-md-4 mb-4">
          <div class="card h-100 text-center">
            <img src="{{ tutor.photo.url }}"
                 alt="{{ tutor.name }}"
                 class="card-img-top"
                 style="width: 100%;
                        height: 300px;
                        object-fit: cover">
            <div class="card-body">
              <h5 class="card-title">{{ tutor.name }}</h5>
              <p class="card-text">
                <strong>Subject:</strong> {{ tutor.course_subject }}
              </p>
              {% if tutor.is_mvp %}<p class="badge bg-warning text-dark">🌟 MVP Tutor</p>{% endif %}
              <a href="{% url 'tutors:tutor' tutor.id %}" class="btn btn-primary mt-2">View Profile</a>
            </div>
          </div>
        </div>
      {% empty %}
        <p>No tutors available at the moment.</p>
      {% endfor %}
    </div>
    <!-- Pagination -->
    <div class="row pagination_row mt-4 mb-4">
      <div class="col">
        <div class="pagination_container d-flex flex-row align-items-center justify-content-start">
          <ul class="pagination_list">
            {% if tutors.has_previous %}
              <li>
                <a href="?page={{ tutors.previous_page_number }}"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
              </li>
            {% endif %}
            {% with start_page=tutors.number|add:"-1"|default:1 %}
              {% with end_page=tutors.number|add:"1"|default:3 %}
                {% for i in tutors.paginator.page_range %}
                  {% if i >= start_page and i <= end_page %}
                    {% if tutors.number == i %}
                      <li class="active">
                        <a href="#">{{ i }}</a>
                      </li>
                    {% else %}
                      <li>
                        <a href="?page={{ i }}">{{ i }}</a>
                      </li>
                    {% endif %}
                  {% endif %}
                {% endfor %}
              {% endwith %}
            {% endwith %}
            {% if tutors.has_next %}
              <li>
                <a href="?page={{ tutors.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
              </li>
            {% endif %}
          </ul>
          <div class="tutors_show_container ml-auto clearfix">
            <div class="tutors_show_text text-white">
              Showing <span class="tutors_showing">{{ tutors.start_index }}-{{ tutors.end_index }}</span> of <span class="tutors_total">{{ tutors.paginator.count }}</span> results
            </div>
            <div class="tutors_show_content text-white">
              <span>Show:</span>
              <form action="" method="GET" id="items_per_page_form">
                <input type="hidden" name="page" value="{{ tutors.number }}">
                {% for key, value in request.GET.items %}
                  {% if key != 'page' and key != 'items_per_page' %}
                    <input type="hidden" name="{{ key }}" value="{{ value }}">
                  {% endif %}
                {% endfor %}
                <select name="items_per_page" onchange="this.form.submit()">
                  <option value="4" {% if items_per_page == 4 %}selected{% endif %}>4</option>
                  <option value="6" {% if items_per_page == 6 %}selected{% endif %}>6</option>
                </select>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}
{% block script %}
  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
  <script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
  <script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
  <script src="{% static 'plugins/easing/easing.js' %}"></script>
  <script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
  <script src="{% static 'plugins/colorbox/jquery.colorbox-min.js' %}"></script>
  <script src="{% static 'js/courses.js' %}"></script>
{% endblock script %}