config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('pages.urls', namespace='pages')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('schools/', include('schools.urls', namespace='schools')),
    path('tutors/', include('tutors.urls', namespace='tutors')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('<int:course_id>/', views.course, name='course'),
    path('search/', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('copyright/', views.copyright, name='copyright'),
    path('terms_of_use/', views.terms_of_use, name='terms_of_use'),
    path('privacy/', views.privacy, name='privacy'),
]

courses/models.py
from django.db import models
from tutors.models import Tutor
from schools.models import School
# adjust path if needed
from .choices import district_choices, subject_choices


class Curriculum(models.Model):
    name = models.CharField(max_length=50,
                            choices=subject_choices,
                            default='Chinese',
                            help_text='Subject matter of the curriculum'
                            )
    text = models.TextField(blank=True,
                            null=True,
                            help_text='Detailed syllabus of the curriculum'
                            )

    def __str__(self):
        return self.name


class Course(models.Model):
    syllabus = models.ManyToManyField(Curriculum, blank=True)

    CLASS_TYPE_CHOICES = [
        ('live', 'Live'),
        ('video', 'Video'),
    ]

    title = models.CharField(
        max_length=200,
        help_text='Name of the course'
    )
    tutor = models.ForeignKey(
        Tutor,
        on_delete=models.DO_NOTHING,
        related_name='courses',
        help_text='Tutor teaching this course'
    )
    school = models.ForeignKey(
        School,
        on_delete=models.DO_NOTHING,
        related_name='courses',
        help_text='School offering the course',
        blank=True,
        null=True,
    )
    district = models.CharField(
        max_length=50,
        choices=district_choices,
        default='Sha Tin',
        help_text='District where the course is offered'
    )
    subject = models.CharField(
        max_length=50,
        choices=subject_choices,
        default='Chinese',
        help_text='Subject matter of the course'
    )
    students_enrolled = models.PositiveIntegerField(
        default=0,
        help_text='Current number of students enrolled'
    )
    max_students = models.PositiveIntegerField(
        default=20,
        help_text='Maximum number of students allowed'
    )
    rating = models.DecimalField(
        max_digits=2,
        decimal_places=1,
        default=0.0,
        help_text='Average rating from 0.0 to 5.0'
    )
    price = models.IntegerField(
        default=500,
        blank=True,
        null=True,
        help_text='Course price in HKD'
    )
    duration = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        default=2.0,
        help_text='Course duration in hours'
    )
    total_classes = models.PositiveIntegerField(
        default=4,
        help_text='Total number of classes in the course'
    )
    class_time = models.CharField(
        max_length=50,
        default='Wed 4 p.m.',
        help_text='Scheduled time for the class (e.g., Wed 4 p.m.)'
    )
    class_type = models.CharField(
        max_length=5,
        choices=CLASS_TYPE_CHOICES,
        default='live',
        help_text='Delivery format of the course'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    description = models.TextField(
        help_text='Detailed description of the course',
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.title

    def enrollment_display(self):
        return f"{self.students_enrolled}/{self.max_students}"

courses/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Course, Curriculum
from tutors.models import Tutor
from schools.models import School
from .choices import district_choices, subject_choices
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def courses(request):
    courses = Course.objects.all()
    items_per_page = int(request.GET.get('items_per_page', 2))
    paginator = Paginator(courses, items_per_page)
    page = request.GET.get('page', 1)
    paged_courses = paginator.get_page(page)

    mvp_tutors = Tutor.objects.all().filter(is_mvp=True)

    context = {
        'courses': paged_courses,
        'mvp_tutors': mvp_tutors,
    }
    return render(request, 'courses/courses.html', context)


def course(request, course_id):
    course = Course.objects.get(id=course_id)
    mvp_tutors = Tutor.objects.all().filter(is_mvp=True)
    courses = Course.objects.all()[:3]
    context = {
        'course': course,
        'mvp_tutors': mvp_tutors,
        'courses': courses,
    }
    return render(request, 'courses/course.html', context)


def search(request):
    queryset_list = Course.objects.order_by('-created_at')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(Q(school__title__icontains=keywords) | Q(
                title__icontains=keywords) | Q(tutor__name__icontains=keywords))
    if 'district' in request.GET:
        district = request.GET['district']
        if district:
            queryset_list = queryset_list.filter(district__iexact=district)
    if 'subject' in request.GET:
        subject = request.GET['subject']
        if subject:
            queryset_list = queryset_list.filter(subject__iexact=subject)
    if 'class_type' in request.GET:
        class_type = request.GET['class_type']
        if class_type:
            queryset_list = queryset_list.filter(class_type__iexact=class_type)
    mvp_tutors = Tutor.objects.all().filter(is_mvp=True)

    # paginator = Paginator(queryset_list, 3)
    # page = request.GET.get('page')
    # paged_courses = paginator.get_page(page)
    context = {
        # 'courses': paged_courses,
        'courses': queryset_list,
        'district_choices': district_choices,
        "subject_choices": subject_choices,
        'mvp_tutors': mvp_tutors,

        "values": request.GET,
    }
    return render(request, 'courses/search.html', context)

templates/courses/search.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
      <link rel="stylesheet"
            type="text/css"
            href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
      <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}"
            rel="stylesheet"
            type="text/css">
      <link href="{% static 'plugins/colorbox/colorbox.css' %}"
            rel="stylesheet"
            type="text/css">
      <link rel="stylesheet"
            type="text/css"
            href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
      <link rel="stylesheet"
            type="text/css"
            href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
      <link rel="stylesheet"
            type="text/css"
            href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
      <link rel="stylesheet"
            type="text/css"
            href="{% static 'styles/courses.css' %}">
      <link rel="stylesheet"
            type="text/css"
            href="{% static 'styles/courses_responsive.css' %}">
      <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock link %}
{% block content %}
      <!-- Home -->
      <div class="home">
            <!--Breadcrumbs-->
            <div class="breadcrumbs_container">
                  <div class="container">
                        <div class="row">
                              <div class="col">
                                    <div class="breadcrumbs">
                                          <ul>
                                                <li>
                                                      <a href="{% url 'pages:index' %}">Home</a>
                                                </li>
                                                <li>
                                                      <a href="{% url 'courses:courses' %}">Courses</a>
                                                </li>
                                                <li>Search Results</li>
                                          </ul>
                                    </div>
                              </div>
                        </div>
                  </div>
            </div>
      </div>
      <!-- Serached Courses -->
      <div class="courses">
            <div class="container">
                  <div class="row">
                        <!-- Courses Main Content -->
                        <div class="col-lg-8">
                              <div class="courses_search_container">
                                    <form action="{% url 'courses:search' %}"
                                          id="courses_search_form"
                                          class="courses_search_form d-flex flex-row align-items-center justify-content-start">
                                          <input type="search"
                                                 class="courses_search_input"
                                                 placeholder="Search Courses"
                                                 name="keywords">
                                          <select id="courses_search_select"
                                                  class="courses_search_select courses_search_input"
                                                  name="class_type">
                                                <option value=''>All Types</option>
                                                <option>live</option>
                                                <option>video</option>
                                          </select>
                                          <button action="submit" class="courses_search_button ml-auto">search now</button>
                                    </form>
                              </div>
                              <div class="courses_container">
                                    <div class="row courses_row">
                                          <!-- Course -->
                                          {% if courses %}
                                                {% for course in courses %}
                                                      <div class="col-lg-6 course_col mt-3">
                                                            <div class="course">
                                                                  <div class="course_image">
                                                                        <img src="{{ course.photo_main.url }}" alt="" height="300px" width="500px">
                                                                  </div>
                                                                  <div class="course_body">
                                                                        <h3 class="course_title">
                                                                              <a href="{% url 'courses:course' course.id %}">{{ course.title }}</a>
                                                                        </h3>
                                                                        <div class="course_teacher">{{ course.tutor.name }}</div>
                                                                        <div class="course_text">
                                                                              <a href="{% url 'courses:course' course.id %}">Click to view more</a>
                                                                        </div>
                                                                        <br />
                                                                        <div class="course_info">
                                                                              <i class="fa fa-university" aria-hidden="true"></i>
                                                                              <span>{{ course.school }}</span>
                                                                              <span class="ml-2 text-capitalize text-info">{{ course.class_type }}</span>
                                                                        </div>
                                                                  </div>
                                                                  <div class="course_footer">
                                                                        <div class="course_footer_content d-flex flex-row align-items-center justify-content-start">
                                                                              <div class="course_info">
                                                                                    <i class="fa fa-graduation-cap" aria-hidden="true"></i>
                                                                                    <span>{{ course.enrollment_display }}</span>
                                                                              </div>
                                                                              <div class="course_info">
                                                                                    <i class="fa fa-star" aria-hidden="true"></i>
                                                                                    <span>{{ course.rating }}</span>
                                                                              </div>
                                                                              <div class="course_price ml-auto">${{ course.price }}</div>
                                                                        </div>
                                                                  </div>
                                                            </div>
                                                      </div>
                                                {% endfor %}
                                          {% else %}
                                                <p>No courses available.</p>
                                          {% endif %}
                                    </div>
                                    <div class="row pagination_row">
                                          <div class="col">
                                                <div class="pagination_container d-flex flex-row align-items-center justify-content-start">
                                                      <ul class="pagination_list">
                                                            <li class="active">
                                                                  <a href="#">1</a>
                                                            </li>
                                                            <li>
                                                                  <a href="#">2</a>
                                                            </li>
                                                            <li>
                                                                  <a href="#">3</a>
                                                            </li>
                                                            <li>
                                                                  <a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                                            </li>
                                                      </ul>
                                                      <div class="courses_show_container ml-auto clearfix">
                                                            <div class="courses_show_text">
                                                                  Showing <span class="courses_showing">1-6</span> of <span class="courses_total">26</span> results:
                                                            </div>
                                                            <div class="courses_show_content">
                                                                  <span>Show:</span>
                                                                  <select id="courses_show_select" class="courses_show_select">
                                                                        <option>06</option>
                                                                        <option>12</option>
                                                                        <option>24</option>
                                                                        <option>36</option>
                                                                  </select>
                                                            </div>
                                                      </div>
                                                </div>
                                          </div>
                                    </div>
                              </div>
                        </div>
                        <!-- Courses Sidebar -->
                        <div class="col-lg-4">
                              <div class="sidebar">
                                    <!--Tutor stars -->
                                    <div class="sidebar_section">
                                          <div class="sidebar_section_title">Tutor stars</div>
                                          <div class="sidebar_latest">
                                                <!-- Tutor star -->
                                                {% if mvp_tutors %}
                                                      {% for tutor in mvp_tutors %}
                                                            <div class="card">
                                                                  <img class="card-img-top" src={{ tutor.photo.url }} alt="Tutor star" />
                                                                  <div class="card-body">
                                                                        <h5 class="card-title">5** Tutor</h5>
                                                                        <h6 class="text-secondary">{{ tutor.name }}</h6>
                                                                        <p class="card-text">{{ tutor.description }}</p>
                                                                  </div>
                                                            </div>
                                                      {% endfor %}
                                                {% endif %}
                                          </div>
                                    </div>
                              </div>
                        </div>
                  </div>
            </div>
      </div>
{% endblock content %}
{% block script %}
      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
      <script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
      <script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
      <script src="{% static 'plugins/easing/easing.js' %}"></script>
      <script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
      <script src="{% static 'plugins/colorbox/jquery.colorbox-min.js' %}"></script>
      <script src="{% static 'js/courses.js' %}"></script>
{% endblock script %}