config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('pages.urls', namespace='pages')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('schools/', include('schools.urls', namespace='schools')),
    path('tutors/', include('tutors.urls', namespace='tutors')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('<int:course_id>/', views.course, name='course'),
    path('search/', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('copyright/', views.copyright, name='copyright'),
    path('terms_of_use/', views.terms_of_use, name='terms_of_use'),
    path('privacy/', views.privacy, name='privacy'),
]

schools/urls.py
from django.urls import path
from . import views

app_name = 'schools'

urlpatterns = [
    path('', views.schools, name='schools'),
    path('<int:school_id>/', views.school, name='school'),
]

schools/models.py
from django.db import models
from datetime import datetime
from courses.choices import district_choices

# Create your models here.


class School(models.Model):
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    district = models.CharField(max_length=20, choices=district_choices)
    room_num = models.IntegerField(default=0)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    is_published = models.BooleanField(default=True)
    office_hr = models.CharField(max_length=200)

    # class Meta:
    #     ordering = ('-title',)
    #     indexes = [models.Index(fields=['list_date'])]

    def __str__(self):
        return self.title

    # def tag_list(self):
    #     return u", ".join(tag.name for tag in self.services.all())

schools/views.py
from django.shortcuts import render, get_object_or_404
from .models import School
from tutors.models import Tutor
from courses.models import Course
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
# Create your views here.


def schools(request):
    # schools = School.objects.all()
    schools = School.objects.order_by('title').filter(is_published=True)
    paginator = Paginator(schools, 3)
    page = request.GET.get('page')
    paged_schools = paginator.get_page(page)
    context = {"schools": paged_schools}
    return render(request, 'schools/schools.html', context)


def school(request, school_id):
    school = get_object_or_404(School, pk=school_id)
    courses = Course.objects.filter(school=school)[:3]
    context = {"school": school, "courses": courses}
    return render(request, 'schools/school.html', context)

templates/schools/school.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    | School - {{ school.title }}
{% endblock title %}
{% block link %}
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
    <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'plugins/colorbox/colorbox.css' %}"
          rel="stylesheet"
          type="text/css">
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'styles/blog_single.css' %}">
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'styles/blog_single_responsive.css' %}">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock link %}
{% block content %}
    <!-- Home (breadcrumbs)-->
    <div class="home">
        <div class="breadcrumbs_container">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="breadcrumbs">
                            <ul>
                                <li>
                                    <a href="{% url 'pages:index' %}">Home</a>
                                </li>
                                <li>
                                    <a href="{% url 'schools:schools' %}">Schools</a>
                                </li>
                                <li>{{ school.title }}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- School -->
    <div class="blog">
        <div class="container">
            <div class="row">
                <!-- Content -->
                <div class="col-lg-8">
                    <div class="blog_content">
                        <div class="blog_title">{{ school.title }}</div>
                        <div class="blog_image">
                            <img src="{{ school.photo_main.url }}" alt="">
                        </div>
                        <div class="blog_subtitle">
                            <i class="fa fa-map-marker" aria-hidden="true"></i> Address: {{ school.address }}
                        </div>
                        <div class="blog_subtitle">
                            <i class="fa fa-graduation-cap" aria-hidden="true"></i> Facility:
                        </div>
                        <div class="blog_images">
                            <div class="row">
                                <div class="col-lg-6 blog_images_col">
                                    <div class="blog_image_small">
                                        <img src="{{ school.photo_1.url }}" alt="">
                                    </div>
                                </div>
                                <div class="col-lg-6 blog_images_col">
                                    <div class="blog_image_small">
                                        <img src="{{ school.photo_2.url }}" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="blog_extra d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start">
                        <div class="blog_social ml-lg-auto">
                            <span>Share:</span>
                            <ul>
                                <li>
                                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Blog Sidebar -->
                <div class="col-lg-4">
                    <div class="sidebar">
                        <!-- Categories -->
                        <div class="sidebar_section">
                            <div class="sidebar_section_title">Information</div>
                            <div class="sidebar_categories">
                                <ul class="categories_list">
                                    <li>
                                        <a href="#" class="clearfix">District:<span>{{ school.district }}</span></a>
                                    </li>
                                    <li>
                                        <a href="#" class="clearfix">Classroom:<span>{{ school.room_num }}</span></a>
                                    </li>
                                    <li>
                                        <a href="#" class="clearfix">Office Hour<span>{{ school.office_hr }}</span></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- Latest Course -->
                        <div class="sidebar_section">
                            <div class="sidebar_section_title">Popular Courses</div>
                            <div class="sidebar_latest">
                                <!-- Latest Course -->
                                {% if courses %}
                                    {% for course in courses %}
                                        <div class="latest d-flex flex-row align-items-start justify-content-start">
                                            <div class="latest_image">
                                                <div>
                                                    <img src="{{ course.photo_main.url }}" alt="">
                                                </div>
                                            </div>
                                            <div class="latest_content">
                                                <div class="latest_title">
                                                    <a href="{% url 'courses:course' course.id %}">{{ course.title }}</a>
                                                </div>
                                                <div class="latest_price">${{ course.price }}</div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                        <!-- Gallery -->
                        <div class="sidebar_section">
                            <div class="sidebar_section_title">Instagram</div>
                            <div class="sidebar_gallery">
                                <ul class="gallery_items d-flex flex-row align-items-start justify-content-between flex-wrap">
                                    <li class="gallery_item">
                                        <div class="gallery_item_overlay d-flex flex-column align-items-center justify-content-center">+</div>
                                        <a class="colorbox" href="{% static 'images/ig1.png' %}">
                                            <img src="{% static 'images/ig1.png' %}" alt="">
                                        </a>
                                    </li>
                                    <li class="gallery_item">
                                        <div class="gallery_item_overlay d-flex flex-column align-items-center justify-content-center">+</div>
                                        <a class="colorbox" href="{% static 'images/ig2.png' %}">
                                            <img src="{% static 'images/ig2.png' %}" alt="">
                                        </a>
                                    </li>
                                    <li class="gallery_item">
                                        <div class="gallery_item_overlay d-flex flex-column align-items-center justify-content-center">+</div>
                                        <a class="colorbox" href="{% static 'images/ig3.png' %}">
                                            <img src="{% static 'images/ig3.png' %}" alt="">
                                        </a>
                                    </li>
                                    <li class="gallery_item">
                                        <div class="gallery_item_overlay d-flex flex-column align-items-center justify-content-center">+</div>
                                        <a class="colorbox" href="{% static 'images/ig4.png' %}">
                                            <img src="{% static 'images/ig4.png' %}" alt="">
                                        </a>
                                    </li>
                                    <li class="gallery_item">
                                        <div class="gallery_item_overlay d-flex flex-column align-items-center justify-content-center">+</div>
                                        <a class="colorbox" href="#">
                                            <img src="#" alt="">
                                        </a>
                                    </li>
                                    <li class="gallery_item">
                                        <div class="gallery_item_overlay d-flex flex-column align-items-center justify-content-center">+</div>
                                        <a class="colorbox" href="#">
                                            <img src="#" alt="">
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- Tags -->
                        <div class="sidebar_section">
                            <div class="sidebar_section_title">Tags</div>
                            <div class="sidebar_tags">
                                <ul class="tags_list">
                                    <li>
                                        <a href="#">DSE</a>
                                    </li>
                                    <li>
                                        <a href="#">5**</a>
                                    </li>
                                    <li>
                                        <a href="#">Universtiy</a>
                                    </li>
                                    <li>
                                        <a href="#">Work hard, Play hard</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</section>
{% endblock %}
{% block script %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
    <script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/easing/easing.js' %}"></script>
    <script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
    <script src="{% static 'plugins/colorbox/jquery.colorbox-min.js' %}"></script>
    <script src="{% static 'js/blog_single.js' %}"></script>
{% endblock script %}

templates/schools/schools.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    | Schools
{% endblock title %}
{% block link %}
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
    <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}"
          rel="stylesheet"
          type="text/css">
    <link href="{% static 'plugins/video-js/video-js.css' %}"
          rel="stylesheet"
          type="text/css">
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'styles/blog.css' %}">
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'styles/blog_responsive.css' %}">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock link %}
{% block content %}
    <!-- Home -->
    <div class="home">
        <div class="breadcrumbs_container">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="breadcrumbs">
                            <ul>
                                <li>
                                    <a href="{% url 'pages:index' %}">Home</a>
                                </li>
                                <li>Schools</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Blog -->
    <div class="blog">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="blog_post_container">
                        <!-- Blog Post -->
                        {% for school in schools %}
                            <div class="blog_post trans_200">
                                <div class="blog_post_image">
                                    <img src="{{ school.photo_main.url }}" alt="">
                                </div>
                                <div class="blog_post_body">
                                    <div class="blog_post_title">
                                        <a href="{% url 'schools:school' school.id %}">{{ school.title }}</a>
                                    </div>
                                    <div class="blog_post_meta">
                                        <div class='container'>
                                            <p>
                                                <i class="fas fa-map-marker-alt"></i> {{ school.district }}
                                            </p>
                                            <p>
                                                <i class="far fa-clock"></i> {{ school.office_hr }}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="blog_post_text">
                                        <p>
                                            Welcome to {{ school.title }}, a premier school in {{ school.district }}. We offer a comprehensive curriculum that covers all subjects, from elementary to high school. Our dedicated teachers are committed to providing a positive and enriching learning experience for each student.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
    <script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/easing/easing.js' %}"></script>
    <script src="{% static 'plugins/masonry/masonry.js' %}"></script>
    <script src="{% static 'plugins/video-js/video.min.js' %}"></script>
    <script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
    <script src="{% static 'js/blog.js' %}"></script>
{% endblock script %}